export const projectData = [
  {
    link: require("../assets/images/project-images/solar-sense.png"),
    name: "Solar Sense",
    desc: "The project enables remote real-time monitoring of photovoltaic energy production via the Solax Cloud API. The responsive application supports Polish and English and includes a demo mode for users without photovoltaic systems. A custom-built proxy server manages CORS headers to ensure secure API communication across browsers.",
    tech_used: "React, TypeScript, Tailwind CSS, Radix UI, PostCSS",
    link_code: "https://github.com/karolfaltyn/solar-sense/",
    link_live: "https://karolfaltyn.github.io/solar-sense/",
  },
  {
    link: require("../assets/images/project-images/zen.png"),
    name: "Zen",
    desc: "A comprehensive management application designed to help you organize tasks, take notes, and manage your time efficiently. It offers a modern, responsive, and intuitive user experience. Additionally, all data is stored in the browser's local storage, ensuring your information is saved securely between sessions.",
    tech_used: "React, TypeScript, Tailwind CSS, Shadcn UI, PostCSS",
    link_code: "https://github.com/karolfaltyn/zen/",
    link_live: "https://karolfaltyn.github.io/zen/",
  },
  {
    link: require("../assets/images/project-images/coffeehouse.png"),
    name: "Coffeehouse",
    desc: "This coffee website offers a user-friendly shopping cart where customers can add, remove, and adjust items with ease. Session storage ensures that cart data is retained throughout the browsing session, providing a smooth and convenient shopping experience.",
    tech_used: "React, JavaScript, Tailwind CSS, PostCSS",
    link_code: "https://github.com/karolfaltyn/coffeehouse/",
    link_live: "https://karolfaltyn.github.io/coffeehouse/",
  },
  {
    link: require("../assets/images/project-images/weather.png"),
    name: "Weather",
    desc: "This app uses an API to display weather data. It shows real-time weather information and forecasts based on either the entered location or the device's geographic location, utilizing the Geolocation API. Weather data is retrieved from the OpenWeatherMap API.",
    tech_used: "React, JavaScript, Tailwind CSS, Material UI Library, PostCSS",
    link_code: "https://github.com/karolfaltyn/weather/",
    link_live: "https://karolfaltyn.github.io/weather/",
  },
  {
    link: require("../assets/images/project-images/abstract.png"),
    name: "Abstract",
    desc: "This project is my response to a challenge from the frontend practice website. The goal is to enhance your HTML and CSS skills by building a visually appealing and responsive website.",
    tech_used: "HTML, CSS",
    link_code: "https://github.com/karolfaltyn/abstract/",
    link_live: "https://karolfaltyn.github.io/abstract/",
  },
];
