export const projectData = [
  {
    link: require("../assets/images/project-images/zen.png"),
    name: "Zen",
    desc: "A comprehensive management application designed to help you organize tasks, take notes, and manage your time efficiently. It offers a modern, responsive, and intuitive user experience. Additionally, all data is stored in the browser's local storage, ensuring your information is saved securely between sessions.",
    tech_used: "HTML, Tailwind CSS, TypeScript, React, PostCSS, Shadcn UI",
    link_code: "https://github.com/karolfaltyn/zen/",
    link_live: "https://karolfaltyn.github.io/zen/",
  },
  {
    link: require("../assets/images/project-images/coffeehouse.png"),
    name: "Coffeehouse",
    desc: "A coffee website with a shopping cart feature allows users to add and delete items, adjust quantities and store data using session storage.",
    tech_used: "HTML, Tailwind CSS, JavaScript, React, PostCSS",
    link_code: "https://github.com/karolfaltyn/coffeehouse/",
    link_live: "https://karolfaltyn.github.io/coffeehouse/",
  },
  {
    link: require("../assets/images/project-images/weather.png"),
    name: "Weather",
    desc: "An application that utilizes an API to display weather data. It can use geographical location or any specified location to show real-time weather information and forecasts. The app uses the OpenWeatherMap API to fetch weather data. ",
    tech_used:
      "HTML, Tailwind CSS, JavaScript, React, PostCSS, Material UI Library",
    link_code: "https://github.com/karolfaltyn/weather/",
    link_live: "https://karolfaltyn.github.io/weather/",
  },
  {
    link: require("../assets/images/project-images/to-do-list.png"),
    name: "To-do List",
    desc: "Project that allow user to store tasks along with their username using the browser's local storage.",
    tech_used: "HTML, Sass / SCSS, JavaScript",
    link_code: "https://github.com/karolfaltyn/to-do-list/",
    link_live: "https://karolfaltyn.github.io/to-do-list/",
  },
  {
    link: require("../assets/images/project-images/number-analyzer.png"),
    name: "Number Analyzer",
    desc: "Web application which generates numbers and categorizes them as even, odd or prime.",
    tech_used: "HTML, CSS, JavaScript, React",
    link_code: "https://github.com/karolfaltyn/number-analyzer/",
    link_live: "https://karolfaltyn.github.io/number-analyzer/",
  },
  {
    link: require("../assets/images/project-images/asteroids.png"),
    name: "Asteroids",
    desc: "A classic arcade-style game from 1979, that allows players to control a spaceship and navigate through an asteroid field, avoiding collisions and shooting asteroids.",
    tech_used: "HTML, JavaScript",
    link_code: "https://github.com/karolfaltyn/asteroids/",
    link_live: "https://karolfaltyn.github.io/asteroids/",
  },
  {
    link: require("../assets/images/project-images/abstract.png"),
    name: "Abstract",
    desc: "This project is my response to a challenge from the frontend practice website. The goal is to enhance your HTML and CSS skills by building a visually appealing and responsive website.",
    tech_used: "HTML, CSS",
    link_code: "https://github.com/karolfaltyn/abstract/",
    link_live: "https://karolfaltyn.github.io/abstract/",
  },
];
